version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - MICROSOFT_CLIENT_ID=${MICROSOFT_CLIENT_ID}
      - MICROSOFT_CLIENT_SECRET=${MICROSOFT_CLIENT_SECRET}
      - MICROSOFT_TENANT_ID=${MICROSOFT_TENANT_ID}
      - MICROSOFT_REDIRECT_URI=${MICROSOFT_REDIRECT_URI}
      - JWT_SECRET=${JWT_SECRET}
      - CANVAS_API_KEY=${CANVAS_API_KEY}
      - WORKDAY_BASE_URL=${WORKDAY_BASE_URL}
      - WORKDAY_CLIENT_ID=${WORKDAY_CLIENT_ID}
      - WORKDAY_CLIENT_SECRET=${WORKDAY_CLIENT_SECRET}
      - CYRIDE_API_KEY=${CYRIDE_API_KEY}
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
